-- begin CECUP_ORDER
alter table CECUP_ORDER add constraint FK_CECUP_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CECUP_CUSTOMER(ID)^
create index IDX_CECUP_ORDER_ON_CUSTOMER on CECUP_ORDER (CUSTOMER_ID)^
-- end CECUP_ORDER
-- begin CECUP_LINE_ITEM
alter table CECUP_LINE_ITEM add constraint FK_CECUP_LINE_ITEM_ON_ORDER foreign key (ORDER_ID) references CECUP_ORDER(ID)^
alter table CECUP_LINE_ITEM add constraint FK_CECUP_LINE_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references CECUP_PRODUCT(ID)^
create index IDX_CECUP_LINE_ITEM_ON_ORDER on CECUP_LINE_ITEM (ORDER_ID)^
create index IDX_CECUP_LINE_ITEM_ON_PRODUCT on CECUP_LINE_ITEM (PRODUCT_ID)^
-- end CECUP_LINE_ITEM
